"use strict";
const DEFAULT_RECEIVER={latitude:38.7467,longitude:-105.1783,label:"Receiver"};
const RINGS=[5,10,15,20,25,30,40,50],MAX_TRAIL=90;
const state={map:null,receiver:DEFAULT_RECEIVER,receiverMarker:null,rings:[],markers:new Map(),trails:new Map(),trailLayers:new Map(),rows:new Map(),selected:null,fit:false,busy:false,locationDirty:false};
const liveAudio={active:false,context:null,nextSequence:0,nextPlayTime:0,sources:new Set(),generation:0};
const num=v=>Number.isFinite(Number(v))?Number(v):null;
const show=(v,d="—")=>v===undefined||v===null||v===""?d:String(v).trim();
const safe=v=>show(v,"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]));
const fmt=v=>num(v)===null?"—":num(v).toLocaleString();
const id=a=>show(a.hex,"unknown").toLowerCase();
const name=a=>show(a.flight,show(a.hex,"Unknown")).trim();
const alt=a=>num(a.alt_baro??a.altitude);
const pos=a=>num(a.lat)!==null&&num(a.lon)!==null?[num(a.lat),num(a.lon)]:null;
function color(feet){if(feet===null)return"#b2c1cc";if(feet<5001)return"#38f45d";if(feet<10001)return"#176b30";if(feet<20001)return"#51c8f3";if(feet<30001)return"#1756ae";if(feet<40001)return"#c9a300";return"#f44336";}
function initMap(){state.map=L.map("map").setView([state.receiver.latitude,state.receiver.longitude],9);L.tileLayer("https://tile.openstreetmap.org/{z}/{x}/{y}.png",{maxZoom:18,attribution:'&copy; <a href="https://www.openstreetmap.org/copyright">OpenStreetMap</a> contributors'}).addTo(state.map);setReceiver(state.receiver);}
function setReceiver(r){state.receiver=r||DEFAULT_RECEIVER;const p=[state.receiver.latitude,state.receiver.longitude];if(state.receiverMarker)state.receiverMarker.remove();state.rings.forEach(x=>x.remove());state.rings=[];state.receiverMarker=L.marker(p,{icon:L.divIcon({className:"",html:'<div class="receiver-dot"></div>',iconSize:[16,16],iconAnchor:[8,8]})}).addTo(state.map).bindPopup(safe(state.receiver.label));RINGS.forEach(mi=>state.rings.push(L.circle(p,{radius:mi*1609.344,color:"#607787",weight:1,dashArray:"5 5",fillOpacity:0}).addTo(state.map)));}
function icon(a,selected){const track=num(a.track)??0;return L.divIcon({className:"",html:`<div class="aircraft-icon ${selected?"selected":""}" style="transform:rotate(${track}deg)">&#9992;</div>`,iconSize:selected?[30,30]:[26,26],iconAnchor:selected?[15,15]:[13,13]});}
function selectAircraft(hex){state.selected=hex;state.markers.forEach((m,k)=>{const a=state.rows.get(k);if(!a)return;m.setIcon(icon(a,k===hex));if(k===hex)m.bindTooltip(name(a),{permanent:true,direction:"top",className:"plane-label"}).openTooltip();else m.unbindTooltip();});renderSelected();renderTable([...state.rows.values()].filter(pos));}
function addTrail(a,p){const hex=id(a);let h=state.trails.get(hex)||[],last=h[h.length-1];if(!last||last[0]!==p[0]||last[1]!==p[1]){h.push([p[0],p[1],alt(a)]);h=h.slice(-MAX_TRAIL);state.trails.set(hex,h);}let layer=state.trailLayers.get(hex);if(!layer){layer=L.layerGroup().addTo(state.map);state.trailLayers.set(hex,layer);}layer.clearLayers();for(let i=1;i<h.length;i++)L.polyline([[h[i-1][0],h[i-1][1]],[h[i][0],h[i][1]]],{color:color(h[i][2]),weight:hex===state.selected?4:3,opacity:.86}).addTo(layer);}
function renderSelected(){const el=document.getElementById("selected-details"),a=state.selected?state.rows.get(state.selected):null;if(!a){el.className="placeholder";el.textContent="Select an aircraft marker or table row.";return;}el.className="details";el.innerHTML=`<div><b>Flight / Hex</b>${safe(name(a))}</div><div><b>ICAO Hex</b>${safe(id(a))}</div><div><b>Altitude</b>${fmt(alt(a))} ft</div><div><b>Speed</b>${fmt(a.speed??a.gs)} kt</div><div><b>Track</b>${fmt(a.track)}°</div><div><b>Seen</b>${fmt(a.seen)} s</div>`;}
function renderTable(rows){rows.sort((a,b)=>(alt(b)??-1)-(alt(a)??-1));const body=document.getElementById("aircraft-rows");if(!rows.length){body.innerHTML='<tr><td class="empty-row" colspan="4">Waiting for positions…</td></tr>';return;}body.innerHTML=rows.map(a=>`<tr data-hex="${safe(id(a))}" class="${id(a)===state.selected?"selected":""}"><td>${safe(name(a))}</td><td>${fmt(alt(a))}</td><td>${fmt(a.speed??a.gs)}</td><td>${fmt(a.seen)}s</td></tr>`).join("");body.querySelectorAll("tr[data-hex]").forEach(row=>row.addEventListener("click",()=>selectAircraft(row.dataset.hex)));}
function updateAircraft(data){const all=Array.isArray(data.aircraft)?data.aircraft:[],located=all.filter(pos),active=new Set();state.rows=new Map(all.map(a=>[id(a),a]));located.forEach(a=>{const hex=id(a),p=pos(a);active.add(hex);let m=state.markers.get(hex);if(!m){m=L.marker(p,{icon:icon(a,hex===state.selected)}).addTo(state.map).on("click",()=>selectAircraft(hex));state.markers.set(hex,m);}else{m.setLatLng(p);m.setIcon(icon(a,hex===state.selected));}m.bindPopup(`<strong>${safe(name(a))}</strong><br>Hex: ${safe(hex)}<br>Altitude: ${fmt(alt(a))} ft`);addTrail(a,p);});state.markers.forEach((m,hex)=>{if(!active.has(hex)){m.remove();state.markers.delete(hex);}});if(!state.fit&&located.length){const b=L.latLngBounds([[state.receiver.latitude,state.receiver.longitude]]);located.forEach(a=>b.extend(pos(a)));state.map.fitBounds(b.pad(.15),{maxZoom:11});state.fit=true;}document.getElementById("position-count").textContent=String(located.length);renderSelected();renderTable(located);}
function renderStatus(s){const d=s.decoder||{},r=s.receiver_roles||{},loc=s.receiver_location||DEFAULT_RECEIVER;if(loc.latitude!==state.receiver.latitude||loc.longitude!==state.receiver.longitude)setReceiver(loc);if(!state.locationDirty){document.getElementById("location-label").value=loc.label||"";document.getElementById("location-latitude").value=loc.latitude;document.getElementById("location-longitude").value=loc.longitude;}const pill=document.getElementById("decoder-pill");pill.textContent=d.running?"Decoder running":"Decoder stopped";pill.className=`pill ${d.running?"running":"stopped"}`;document.getElementById("messages").textContent=fmt(d.messages);document.getElementById("aircraft-count").textContent=fmt(d.aircraft_count);document.getElementById("adsb-role").textContent=r.adsb?`${r.adsb.serial} / #${r.adsb.index}`:"—";document.getElementById("audio-role").textContent=r.audio?`${r.audio.serial} / #${r.audio.index}`:"—";document.getElementById("profile").textContent=d.profile?`${d.profile.sample_rate_sps/1000000} MS/s · ${d.profile.gain_db} dB`:"—";document.getElementById("receiver-label").textContent=loc.label||"Receiver";document.getElementById("last-update").textContent=`Updated ${new Date().toLocaleTimeString()}`;}
function renderAudio(a,live){const badge=document.getElementById("audio-state"),progress=document.getElementById("audio-progress"),player=document.getElementById("audio-playback");document.getElementById("audio-role").textContent=(live.audio_role||a.audio_role)?`${(live.audio_role||a.audio_role).serial} / #${(live.audio_role||a.audio_role).index}`:"—";if(liveAudio.active){badge.textContent="Live";progress.textContent="Listening live to NOAA audio…";player.classList.remove("ready");return;}if(live.running){badge.textContent="Live";progress.textContent="Live NOAA listening is active. Press Stop before starting playback in this tab.";player.classList.remove("ready");return;}badge.textContent=a.running?"Recording":a.recording_ready?"Ready":"Idle";if(a.running){progress.textContent=`Recording NOAA audio… ${a.remaining_seconds??""} seconds remaining`;player.classList.remove("ready");}else if(a.recording_ready){const m=a.metrics||{};progress.textContent=`Latest recording: ${show(m.duration_seconds,"—")} seconds · RMS ${show(m.rms_sample,"—")} · clipping ${show(m.clipped_percent,"—")}%`;if(player.dataset.current!==a.latest_recording_url){player.src=`${a.latest_recording_url}?t=${Date.now()}`;player.dataset.current=a.latest_recording_url;}player.classList.add("ready");}else{progress.textContent="No recording captured this session.";player.classList.remove("ready");}}
async function refreshAudio(){const [recordingResponse,liveResponse]=await Promise.all([fetch("/api/audio/status",{cache:"no-store"}),fetch("/api/audio/live/status",{cache:"no-store"})]);if(recordingResponse.ok&&liveResponse.ok)renderAudio(await recordingResponse.json(),await liveResponse.json());}
async function refresh(){try{const s=await fetch("/api/status",{cache:"no-store"}).then(r=>r.json());renderStatus(s);if(s.decoder?.running&&s.decoder?.json_ready){const a=await fetch("/api/aircraft",{cache:"no-store"});if(a.ok)updateAircraft(await a.json());}await refreshAudio();}catch(e){const p=document.getElementById("decoder-pill");p.textContent="Backend offline";p.className="pill stopped";document.getElementById("last-update").textContent=e.message;}}
async function saveReceiverLocation(){if(state.busy)return;const result=document.getElementById("location-result");const payload={label:document.getElementById("location-label").value,latitude:Number(document.getElementById("location-latitude").value),longitude:Number(document.getElementById("location-longitude").value)};state.busy=true;document.querySelectorAll("button").forEach(b=>b.disabled=true);try{const response=await fetch("/api/settings/receiver-location",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(payload)});const data=await response.json();if(!response.ok)throw new Error(data.error||"Unable to save receiver location");state.locationDirty=false;result.textContent=data.decoder_restart_required?"Saved; restart decoder to apply decoder home position.":"Saved.";await refresh();}catch(error){result.textContent=error.message;}finally{state.busy=false;document.querySelectorAll("button").forEach(b=>b.disabled=false);}}
async function decoder(command){if(state.busy)return;state.busy=true;document.querySelectorAll("button").forEach(b=>b.disabled=true);try{await fetch(`/api/decoder/${command}`,{method:"POST"});await refresh();}finally{state.busy=false;document.querySelectorAll("button").forEach(b=>b.disabled=false);}}
async function audioCommand(command){if(state.busy)return;state.busy=true;document.querySelectorAll("button").forEach(b=>b.disabled=true);try{await fetch(`/api/audio/${command}`,{method:"POST"});await refreshAudio();}finally{state.busy=false;document.querySelectorAll("button").forEach(b=>b.disabled=false);}}
async function startLiveAudio(){if(liveAudio.active||state.busy)return;state.busy=true;document.querySelectorAll("button").forEach(b=>b.disabled=true);try{const response=await fetch("/api/audio/noaa/live/start",{method:"POST"});if(!response.ok)throw new Error("Unable to start live NOAA audio");const AudioContextClass=window.AudioContext||window.webkitAudioContext;liveAudio.context=liveAudio.context||new AudioContextClass();await liveAudio.context.resume();liveAudio.active=true;liveAudio.nextSequence=0;liveAudio.nextPlayTime=liveAudio.context.currentTime+.15;liveAudio.generation+=1;pollLiveAudio(liveAudio.generation);await refreshAudio();}finally{state.busy=false;document.querySelectorAll("button").forEach(b=>b.disabled=false);}}
async function pollLiveAudio(generation){while(liveAudio.active&&generation===liveAudio.generation){try{const response=await fetch(`/api/audio/live/chunk.wav?after=${liveAudio.nextSequence}`,{cache:"no-store"});if(response.status===204){await new Promise(resolve=>setTimeout(resolve,100));continue;}if(!response.ok)throw new Error("Live NOAA segment request failed");liveAudio.nextSequence=Number(response.headers.get("X-Audio-Sequence")||liveAudio.nextSequence+1);const bytes=await response.arrayBuffer();const buffer=await liveAudio.context.decodeAudioData(bytes.slice(0));const source=liveAudio.context.createBufferSource();source.buffer=buffer;source.connect(liveAudio.context.destination);const when=Math.max(liveAudio.nextPlayTime,liveAudio.context.currentTime+.04);source.start(when);liveAudio.nextPlayTime=when+buffer.duration;liveAudio.sources.add(source);source.onended=()=>liveAudio.sources.delete(source);}catch(error){document.getElementById("audio-progress").textContent=error.message;await stopLiveAudio();break;}}}
async function stopLiveAudio(){if(!liveAudio.active){await fetch("/api/audio/live/stop",{method:"POST"});return;}liveAudio.active=false;liveAudio.generation+=1;liveAudio.sources.forEach(source=>{try{source.stop();}catch(error){void error;}});liveAudio.sources.clear();await fetch("/api/audio/live/stop",{method:"POST"});await refreshAudio();}
async function stopAllAudio(){await stopLiveAudio();await audioCommand("stop");}
document.addEventListener("DOMContentLoaded",()=>{initMap();document.getElementById("start-decoder").onclick=()=>decoder("start");document.getElementById("stop-decoder").onclick=()=>decoder("stop");document.getElementById("listen-noaa").onclick=()=>startLiveAudio();document.getElementById("record-noaa").onclick=()=>audioCommand("noaa/start");document.getElementById("stop-audio").onclick=()=>stopAllAudio();document.getElementById("save-location").onclick=()=>saveReceiverLocation();["location-label","location-latitude","location-longitude"].forEach(id=>document.getElementById(id).addEventListener("input",()=>{state.locationDirty=true;}));refresh();setInterval(refresh,2000);});
